# Generated by Django 4.2.6 on 2024-10-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_funeraria_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('descripcion', models.TextField()),
                ('edad', models.IntegerField()),
                ('vacunas_al_dia', models.CharField(max_length=50)),
                ('documento_vacunas', models.ImageField(blank=True, null=True, upload_to='documentos_vacunas/')),
                ('motivo', models.TextField()),
                ('nombre', models.TextField()),
                ('contacto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
