# Generated by Django 5.1.2 on 2024-11-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_donacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cementerio',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviciosmascotas',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
