# Generated by Django 4.2.6 on 2024-10-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_funeraria_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('descripcion', models.TextField()),
                ('edad', models.IntegerField()),
                ('vacunas_al_dia', models.CharField(max_length=50)),
                ('documento_vacunas', models.ImageField(blank=True, null=True, upload_to='documentos_vacunas/')),
                ('motivo', models.TextField()),
                ('nombre', models.TextField()),
                ('contacto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
