# Generated by Django 5.1.1 on 2024-10-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciosmascotas',
            options={'managed': True},
        ),
    ]
